### ISSUE TITLE
After updating plugin, all hidden / removed commands were gone

### ISSUE THREAD

**Issue by pjindras** [TheNextLvl-net/commander#16]
Hello, after updating plugin, all the commands that were hidden / removed are back.

I still have commands.json with those commands, but it is not working now.

**Comment by NonSwag** [comment]
The latest major update (from 3.1.1 to 4.0.0) contains breaking changes
you'd have to adapt to the new format. The easiest to do so is by looking into your old commands.json and hide/unregister and override all permissions again
one known _issue_ with this is that wildcards `*` are no longer supported in the new files
Until the command accepts wildcards again, you either have to do enter every command manually instead of using *
Or temporarily downgrade to 3.1.1

**Comment by NonSwag** [comment]
I know it is a bit late for it, but I added a disclaimer into the README
